version: '3.1'

services:
  api:
    container_name: nest_api
    build: .
    ports: 
      - ${API_PORT}:${API_PORT}
    volumes: 
      - .:/home/api
      - /home/api/node_modules
  db:
    container_name: nest_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
